name: PacketPlots
main: net.dashmc.plots.PacketPlots
version: ${project.version}

authors:
  - Tandhjulet
  - Vqlde

commands:
  plot:
    usage: /<command>
    permission: '*'
    description: Manage the PacketPlots plugin