name: PacketPlots
main: net.dashmc.plots.PacketPlots
version: ${project.version}

authors:
  - Tandhjulet
  - Vqlde

softdepend:
  - Vulcan
  - packetevents
  - HeadDatabase

# commands:
#   plot:
#     usage: /<command>
#     permission: '*'
#     description: Manage the PacketPlots plugin